dataset:
  name: pomegranate_growth_stage
  image_size: 640
  num_classes: 3

  yolo:
    root: AUTO
    train: train
    val: val
    test: test

  classes:
    - immature
    - mature
    - overripe


training:
  epochs: 30
  learning_rate: 0.01
  momentum: 0.937
  weight_decay: 0.0005


dataloader:
  batch_size: 16
  num_workers: 2
  pin_memory: true
